# Generated by Django 4.1.7 on 2023-05-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_atom_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='atom',
            name='atom_name',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
